spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: api-gateway
        url: http://localhost:8086
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/taxi-realm/protocol/openid-connect/certs
  cloud:
    gateway:
      metrics:
        enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: passengers-service-route
          uri: lb://passengers-service
          predicates:
            - Path=/api/passengers/**
          filters:
            - name: RoutingTimeFilter
            - name: CircuitBreaker
              args:
                name: passenger-cb
                fallbackUri: forward:/fallback/passenger

        - id: drivers-service-route
          uri: lb://drivers-service
          predicates:
            - Path=/api/drivers/**, /api/cars/**, /api/assignments/**
          filters:
            - name: RoutingTimeFilter
            - name: CircuitBreaker
              args:
                name: drivers-cb
                fallbackUri: forward:/fallback/driver

        - id: rides-service-route
          uri: lb://rides-service
          predicates:
            - Path=/api/rides/**
          filters:
            - name: RoutingTimeFilter
            - name: CircuitBreaker
              args:
                name: rides-cb
                fallbackUri: forward:/fallback/rides

        - id: authentication-server-route
          uri: lb://authentication-server
          predicates:
            - Path=/api/auth/**
          filters:
            - name: RoutingTimeFilter
            - name: CircuitBreaker
              args:
                name: auth-cb
                fallbackUri: forward:/fallback/auth

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: RoutingTimeFilter
            - name: CircuitBreaker
              args:
                name: notification-cb
                fallbackUri: forward:/fallback/notification

        - id: payment-service-route
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - name: RoutingTimeFilter
            - name: CircuitBreaker
              args:
                name: payment-cb
                fallbackUri: forward:/fallback/payment

        - id: promocode-service-route
          uri: lb://promocode-service
          predicates:
            - Path=/api/promocodes/**
          filters:
            - name: RoutingTimeFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter.configs:
    default:
      timeout-duration:
        seconds: 3

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    tags:
      application: api-gateway

---
spring:
  config:
    activate:
      on-profile: docker
  boot:
    admin:
      client:
        url: http://admin-server:8086
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/taxi-realm/protocol/openid-connect/certs

logging:
  config: classpath:logback-docker.xml

management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
