server:
  # must be configured in environment (i.e. docker compose)
  port: ${SERVER_PORT}
  # The stop processing uses a timeout which provides a grace period during which existing requests will be allowed to complete but no new requests will be permitted
  shutdown: graceful

spring:
  cloud:
    config:
      # Allow the microservices to override the remote properties with their own System properties or config file
      allow-override: true
      # Override configuration with any local property source
      override-none: true

# Logging
logging.level.org.springframework: INFO
