spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: promocode-service
        url: http://localhost:8086
  datasource:
    url:      jdbc:postgresql://localhost:5432/promocodes_db
    username: postgres
    password: ${POSTGRES_PASSWORD:root}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/taxi-realm/protocol/openid-connect/certs

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    liquibase: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
  boot:
    admin:
      client:
        url: http://admin-server:8086
  datasource:
    url:      jdbc:postgresql://postgres:5432/promocodes_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/taxi-realm/protocol/openid-connect/certs

management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans

logging:
  config: classpath:logback-docker.xml

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
